name: garage_manager_flutter
description: "A simple university project developed with Flutter, more informations on README page."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  google_fonts:
  http:
  flutter_lucide:
  url_launcher:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/
  uses-material-design: true
